export const URDU_CHAR_MAP: StringMap = {
  ا: "a",
  آ: "aa",
  ع: "a",
  ء: "",
  و: "o",
  ی: "i",
  ے: "e",
  ب: "b",
  پ: "p",
  ت: "t",
  ٹ: "t",
  ث: "s",
  ج: "j",
  چ: "ch",
  ح: "h",
  خ: "kh",
  د: "d",
  ڈ: "d",
  ذ: "z",
  ر: "r",
  ڑ: "r",
  ز: "z",
  س: "s",
  ش: "sh",
  ص: "s",
  ض: "z",
  ط: "t",
  ظ: "z",
  غ: "gh",
  ف: "f",
  ق: "q",
  ک: "k",
  گ: "g",
  ل: "l",
  م: "m",
  ن: "n",
  ں: "n",
  ہ: "h",
  ئ: "i",
  ؤ: "o",
  ھ: "h",
  ۂ: "e",
  ۓ: "e",
  ك: "k",
  ي: "i",
  "\u064E": "a",
  "\u0650": "i",
  "\u064F": "u",
  "\u0652": "",
  "\u06DF": "",
  "\u06E0": "",
  "\u0651": "",
  "\u0640": "",
  "\u0670": "a",
  "\u064B": "an",
  "،": ",",
  "؟": "?",
  "۔": ".",
};

export const WORD_PRIORITY_MAP: StringMap = {
  ہے: "hai",
  ہوں: "hoon",
  ہیں: "hain",
  تھا: "tha",
  تھی: "thi",
  تھے: "the",
  میں: "mein",
  ہم: "hum",
  وہ: "woh",
  یہ: "yeh",
  آپ: "aap",
  تو: "to",
  ہی: "hi",
  کیا: "kya",
  کو: "ko",
  سے: "se",
  پر: "par",
  اور: "aur",
  اگر: "agar",
  لیکن: "lekin",
  یہاں: "yahan",
  یہیں: "yahin",
  بھی: "bhi",
  ہوئے: "hue",
  اترتا: "utarta",
  بہن: "behan",
  بھائی: "bhai",
  "سوتیلا بھائی": "sotela bhai",
  ماں: "maan",
  باپ: "baap",
  بیٹا: "beta",
  بیٹی: "beti",
  چاچا: "chacha",
  ماموں: "mamoo",
  خالہ: "khala",
  پھوپھی: "phuphi",
  نانی: "nani",
  دادا: "dada",
  دادی: "dadi",
  پوتا: "pota",
  پوتی: "poti",
  نواسہ: "nawasa",
  نواسی: "nawasi",
  یتیم: "yateem",
  عبادت: "ibadat",
  محبت: "muhabbat",
  دعاؤں: "duaon",
  روح: "rooh",
  دل: "dil",
  اللہ: "Allah",
  محمد: "Muhammad",
  رسول: "Rasool",
  نبی: "Nabi",
  قرآن: "Quran",
  حدیث: "Hadith",
  اسلام: "Islam",
  مسلمان: "Muslim",
  ایمان: "Iman",
  نماز: "Namaz",
  روزہ: "Roza",
  زکوٰۃ: "Zakat",
  حج: "Hajj",
  صدقہ: "Sadaqah",
  جنت: "Jannat",
  دوزخ: "Dozakh",
  آخرت: "Aakhirat",
  شریعت: "Shariat",
  فقہ: "Fiqh",
  قیامت: "Qayamat",
  "الحمد للہ": "Alhamdulillah",
  "ان شاء اللہ": "InshaAllah",
  "ما شاء اللہ": "MashaAllah",
  "جزاک اللہ": "JazakAllah",
  "اللہ اکبر": "Allahu Akbar",
  "السلام علیکم": "Assalamu Alaikum",
  "وعلیکم السلام": "Wa Alaikum Assalam",
  "رحمت اللہ": "Rahmatullah",
  برکاتہ: "Barakatuh",
  حسن: "Hasan",
  حسین: "Husain",
  علی: "Ali",
  فاطمہ: "Fatima",
  عائشہ: "Aisha",
  عمر: "Umar",
  عثمان: "Usman",
  ابوبکر: "Abu Bakr",
};

const escapeRegExp = (str: string): string => str.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");

const DICTIONARY_REGEX: RegExp = new RegExp(
  `(?<![\\p{L}\\p{M}])(?:${Object.keys(WORD_PRIORITY_MAP)
    .sort((a: string, b: string) => b.length - a.length)
    .map(escapeRegExp)
    .join("|")})(?![\\p{L}\\p{M}])`,
  "gu",
);

const CHAR_REGEX: RegExp = new RegExp(
  Object.keys(URDU_CHAR_MAP)
    .sort((a: string, b: string) => b.length - a.length)
    .map(escapeRegExp)
    .join("|"),
  "g",
);

export function romanizeUrdu(text: string): string {
  if (!text) return "";

  return text
    .normalize("NFC")
    .replace(DICTIONARY_REGEX, (match: string): string => WORD_PRIORITY_MAP[match] || match)
    .replace(CHAR_REGEX, (match: string): string => URDU_CHAR_MAP[match] || match);
}

export default romanizeUrdu;

type StringMap = Readonly<Record<string, string>>;
