import { Schema } from "../schema";

export const jss: Schema = {
  ADDITIONAL_FEATURES: [
    {
      FEATURE: "syllable",
      // if the syllable contains a qamets qatan character
      HEBREW: /\u{05C7}/u,
      TRANSLITERATION: (syllable) => {
        const next = syllable?.next?.value?.text;
        // if the next syllable includes a hateph qamets, then replace the qamets qatan with a regular qamets
        if (next && next.includes("\u05B3")) {
          return syllable.text.replace("\u{05C7}", "\u{05B8}");
        }
        return syllable.text;
      },
    },
  ],
  ALEF: "ʾ",
  AYIN: "ʿ",
  BET: "ḇ",
  BET_DAGESH: "b",
  DAGESH: "",
  DAGESH_CHAZAQ: true,
  DALET: "ḏ",
  DALET_DAGESH: "d",
  DIVINE_NAME: "yhwh",
  FINAL_KAF: "ḵ",
  FINAL_MEM: "m",
  FINAL_NUN: "n",
  FINAL_PE: "p̄",
  FINAL_TSADI: "ṣ",
  FURTIVE_PATAH: "a",
  GIMEL: "ḡ",
  GIMEL_DAGESH: "g",
  HATAF_PATAH: "ă",
  HATAF_QAMATS: "å̆",
  HATAF_SEGOL: "ɛ̆",
  HE: "h",
  HET: "ḥ",
  HIRIQ: "i",
  HIRIQ_YOD: "ī",
  HOLAM: "ō",
  HOLAM_HASER: "ō",
  HOLAM_VAV: "ō",
  KAF: "ḵ",
  KAF_DAGESH: "k",
  LAMED: "l",
  MAQAF: " ",
  MEM: "m",
  MS_SUFX: "å̄yw",
  NUN: "n",
  PASEQ: "",
  PATAH: "a",
  PE: "p̄",
  PE_DAGESH: "p",
  QAMATS: "å̄",
  QAMATS_HE: "å̄",
  QAMATS_QATAN: "å",
  QOF: "q",
  QUBUTS: "u",
  RESH: "r",
  SAMEKH: "s",
  SEGOL: "ɛ",
  SEGOL_HE: "ɛ",
  SEGOL_YOD: "ɛ",
  SHIN: "š",
  SHUREQ: "ū",
  SIN: "ś",
  SOF_PASUQ: "",
  TAV: "ṯ",
  TAV_DAGESH: "t",
  TET: "ṭ",
  TSADI: "ṣ",
  TSERE: "ē",
  TSERE_HE: "ē",
  TSERE_YOD: "ē",
  VAV: "w",
  VOCAL_SHEVA: "ə",
  YOD: "y",
  ZAYIN: "z",
  allowNoNiqqud: true,
  article: true,
  holemHaser: "remove",
  longVowels: true,
  qametsQatan: true,
  shevaAfterMeteg: true,
  sqnmlvy: true,
  strict: false,
  wawShureq: true,
};
